### ISSUE TITLE
Enhancement Feature Discusion

### ISSUE THREAD

**Issue by Oxika95** [schnatterer/rooted-graphene#49]
GrapheneOS prides itself on its hardening by using the user feature to isolate apps from each other. Is there a way to make a user profile that is not exposed to magisk so that the apps therein do not have root access, ie banking etc... I am fairly novice when it comes to these things but this is how linux tends to operate right? Root user with elevated access that you shouldn't really use in most cases then standard user with restricted or "standard" permissions. Does android not function in this way?

**Comment by schnatterer** [comment]
This is way beyond the scope of this project.
There is magisk hide and zygisk and what not. Zygisk won't work on GrapheneOS, see big box right at the beginning of the Readme.
